In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"C:\Data\data.csv")
df.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z,2,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z,2,0
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z,2,0
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z,2,0
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z,2,0

In [3]:
import os
print(os.getcwd())

C:\Users\Soret\credit-risk-model\notebooks

In [4]:
%cd C:\Users\Soret\credit-risk-model

C:\Users\Soret\credit-risk-model

In [5]:
import sys
sys.path.append(r"C:\Users\Soret\credit-risk-model")

In [6]:
from src.data_processing import process_data

In [8]:
import pandas as pd
from src.data_processing import process_data

df = pd.read_csv(r"C:\Data\data.csv")

In [6]:
DROP_COLS = [
    "TransactionId",
    "BatchId",
    "AccountId",
    "SubscriptionId",
    "CustomerId"
]

In [9]:
print(X_processed.shape)

X_fe = df.copy()

for step in pipeline.feature_engineering_steps:
    X_fe = step.transform(X_fe)

print(X_fe.columns.tolist())
print("\nNumber of columns:", len(X_fe.columns))

(95662, 201525)
['TransactionId', 'BatchId', 'AccountId', 'SubscriptionId', 'CustomerId', 'CurrencyCode', 'CountryCode', 'ProviderId', 'ProductId', 'ProductCategory', 'ChannelId', 'Amount', 'Value', 'TransactionStartTime', 'PricingStrategy', 'FraudResult', 'TotalTransactionAmount', 'AverageTransactionAmount', 'TransactionCount', 'StdTransactionAmount', 'TransactionHour', 'TransactionDay', 'TransactionMonth', 'TransactionYear']

Number of columns: 24

In [10]:
for col in [
    "TransactionId",
    "BatchId",
    "AccountId",
    "SubscriptionId",
    "CustomerId",
    "CurrencyCode"
]:
    if col in X_fe.columns:
        print(col, X_fe[col].nunique())

TransactionId 95662
BatchId 94809
AccountId 3633
SubscriptionId 3627
CustomerId 3742
CurrencyCode 1

In [14]:
drop_cols = [
    "TransactionId",
    "BatchId",
    "AccountId",
    "SubscriptionId",
    "CustomerId"
]

In [16]:
df = df.drop(columns=drop_cols, errors="ignore")

In [9]:
from src.data_processing import process_data

X_processed, pipeline = process_data(df)

print(X_processed.shape)

(95662, 51)

In [14]:
df.columns

Index(['TransactionId', 'BatchId', 'AccountId', 'SubscriptionId', 'CustomerId',
       'CurrencyCode', 'CountryCode', 'ProviderId', 'ProductId',
       'ProductCategory', 'ChannelId', 'Amount', 'Value',
       'TransactionStartTime', 'PricingStrategy', 'FraudResult'],
      dtype='str')

In [12]:
customer_agg = df.groupby("CustomerId").agg(
    TotalTransactionAmount=("Amount", "sum")
).reset_index()

In [4]:
customer_agg

           CustomerId  TotalTransactionAmount
0        CustomerId_1                -10000.0
1       CustomerId_10                -10000.0
2     CustomerId_1001                 20000.0
3     CustomerId_1002                  4225.0
4     CustomerId_1003                 20000.0
...               ...                     ...
3737   CustomerId_992                 20000.0
3738   CustomerId_993                 20000.0
3739   CustomerId_994                543873.0
3740   CustomerId_996                139000.0
3741   CustomerId_998                100000.0

[3742 rows x 2 columns]

In [38]:
customer_agg = df.groupby("CustomerId").agg(
    TotalTransactionAmount=("Amount", "sum"),
    AvgTransactionAmount=("Amount", "mean"),
    MaxTransactionAmount=("Amount", "max"),
    MinTransactionAmount=("Amount", "min"),
    TransactionCount=("Amount", "count"),
    TotalValue=("Value", "sum"),
    AvgValue=("Value", "mean"),
    StdTransactionAmount=("Amount", "std")
).reset_index()

In [39]:
df = df.merge(customer_agg, on="CustomerId", how="left")

In [40]:
df

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,...,AvgValue_x,TotalTransactionAmount_y,TotalTransactionAmount,AvgTransactionAmount_y,MaxTransactionAmount_y,MinTransactionAmount_y,TransactionCount_y,TotalValue_y,AvgValue_y,StdTransactionAmount
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,...,1713.000000,109921.75,109921.75,923.712185,20000.0,-5000.0,119,203847,1713.000000,3042.294251
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,...,1713.000000,109921.75,109921.75,923.712185,20000.0,-5000.0,119,203847,1713.000000,3042.294251
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,...,500.000000,1000.00,1000.00,500.000000,500.0,500.0,2,1000,500.000000,0.000000
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,...,7542.710526,228727.20,228727.20,6019.136842,100000.0,-10000.0,38,286623,7542.710526,17169.241610
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,...,7542.710526,228727.20,228727.20,6019.136842,100000.0,-10000.0,38,286623,7542.710526,17169.241610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,UGX,256,ProviderId_4,ProductId_6,financial_services,...,4435.008726,2438140.00,2438140.00,4255.043630,235000.0,-5000.0,573,2541260,4435.008726,22554.029939
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,UGX,256,ProviderId_6,ProductId_10,airtime,...,1467.837209,58499.60,58499.60,1360.455814,10000.0,-1000.0,43,63117,1467.837209,2274.756582
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,UGX,256,ProviderId_4,ProductId_6,financial_services,...,1467.837209,58499.60,58499.60,1360.455814,10000.0,-1000.0,43,63117,1467.837209,2274.756582
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,UGX,256,ProviderId_6,ProductId_19,tv,...,1906.246183,851985.00,851985.00,1625.925573,23000.0,-5000.0,524,998873,1906.246183,3207.920536
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,UGX,256,ProviderId_4,ProductId_6,financial_services,...,1906.246183,851985.00,851985.00,1625.925573,23000.0,-5000.0,524,998873,1906.246183,3207.920536

In [41]:
import pandas as pd

# Ensure datetime format
df["TransactionStartTime"] = pd.to_datetime(df["TransactionStartTime"])

# Extract time-based features
df["TransactionHour"] = df["TransactionStartTime"].dt.hour
df["TransactionDay"] = df["TransactionStartTime"].dt.day
df["TransactionMonth"] = df["TransactionStartTime"].dt.month
df["TransactionYear"] = df["TransactionStartTime"].dt.year

In [43]:
high_card_cols = [col for col in cat_cols if df[col].nunique() > 100]
low_card_cols = [col for col in cat_cols if df[col].nunique() <= 100]

In [44]:
df_onehot = pd.get_dummies(
    df,
    columns=low_card_cols,
    drop_first=True
)

In [45]:
df_onehot

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CountryCode,Amount,Value,TransactionStartTime,PricingStrategy,...,ProductCategory_financial_services,ProductCategory_movies,ProductCategory_other,ProductCategory_ticket,ProductCategory_transport,ProductCategory_tv,ProductCategory_utility_bill,ChannelId_ChannelId_2,ChannelId_ChannelId_3,ChannelId_ChannelId_5
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,256,1000.0,1000,2018-11-15 02:18:49+00:00,2,...,False,False,False,False,False,False,False,False,True,False
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,256,-20.0,20,2018-11-15 02:19:08+00:00,2,...,True,False,False,False,False,False,False,True,False,False
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,256,500.0,500,2018-11-15 02:44:21+00:00,2,...,False,False,False,False,False,False,False,False,True,False
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,256,20000.0,21800,2018-11-15 03:32:55+00:00,2,...,False,False,False,False,False,False,True,False,True,False
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,256,-644.0,644,2018-11-15 03:34:21+00:00,2,...,True,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,256,-1000.0,1000,2019-02-13 09:54:09+00:00,2,...,True,False,False,False,False,False,False,True,False,False
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,256,1000.0,1000,2019-02-13 09:54:25+00:00,2,...,False,False,False,False,False,False,False,False,True,False
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,256,-20.0,20,2019-02-13 09:54:35+00:00,2,...,True,False,False,False,False,False,False,True,False,False
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,256,3000.0,3000,2019-02-13 10:01:10+00:00,2,...,False,False,False,False,False,True,False,False,True,False
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,256,-60.0,60,2019-02-13 10:01:28+00:00,2,...,True,False,False,False,False,False,False,True,False,False

In [46]:
missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing.sort_values(ascending=False))

StdTransactionAmount    712
dtype: int64

In [47]:
from sklearn.impute import SimpleImputer

# Identify columns
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
cat_cols = df.select_dtypes(include=["object", "string"]).columns

# Numeric imputation (median)
num_imputer = SimpleImputer(strategy="median")
df[num_cols] = num_imputer.fit_transform(df[num_cols])

# Categorical imputation (mode)
cat_imputer = SimpleImputer(strategy="most_frequent")
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

In [48]:
cat_imputer
df[cat_cols]

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,ProviderId,ProductId,ProductCategory,ChannelId
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,ProviderId_6,ProductId_10,airtime,ChannelId_3
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,ProviderId_4,ProductId_6,financial_services,ChannelId_2
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,ProviderId_6,ProductId_1,airtime,ChannelId_3
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,ProviderId_1,ProductId_21,utility_bill,ChannelId_3
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,ProviderId_4,ProductId_6,financial_services,ChannelId_2
...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,UGX,ProviderId_4,ProductId_6,financial_services,ChannelId_2
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,UGX,ProviderId_6,ProductId_10,airtime,ChannelId_3
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,UGX,ProviderId_4,ProductId_6,financial_services,ChannelId_2
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,UGX,ProviderId_6,ProductId_19,tv,ChannelId_3
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,UGX,ProviderId_4,ProductId_6,financial_services,ChannelId_2

In [49]:
from sklearn.preprocessing import MinMaxScaler

# Select numerical columns
num_cols = df.select_dtypes(include=["int64", "float64"]).columns

# Apply Min-Max Normalization
minmax_scaler = MinMaxScaler()
df[num_cols] = minmax_scaler.fit_transform(df[num_cols])

In [50]:
from sklearn.preprocessing import StandardScaler

# Select numerical columns
num_cols = df.select_dtypes(include=["int64", "float64"]).columns

# Apply Standardization
standard_scaler = StandardScaler()
df[num_cols] = standard_scaler.fit_transform(df[num_cols])

In [51]:
standard_scaler
df[num_cols]

,CountryCode,Amount,Value,PricingStrategy,FraudResult,TotalTransactionAmount_x,AvgTransactionAmount_x,MaxTransactionAmount_x,MinTransactionAmount_x,TransactionCount_x,...,AvgValue_x,TotalTransactionAmount_y,TotalTransactionAmount,AvgTransactionAmount_y,MaxTransactionAmount_y,MinTransactionAmount_y,TransactionCount_y,TotalValue_y,AvgValue_y,StdTransactionAmount
0,0.0,-0.046371,-0.072291,-0.349252,-0.044962,0.170118,-0.067623,-0.193027,0.163927,-0.311831,...,-0.095799,0.170118,0.170118,-0.067623,-0.193027,0.163927,-0.311831,-0.244587,-0.095799,-0.167524
1,0.0,-0.054643,-0.080251,-0.349252,-0.044962,0.170118,-0.067623,-0.193027,0.163927,-0.311831,...,-0.095799,0.170118,0.170118,-0.067623,-0.193027,0.163927,-0.311831,-0.244587,-0.095799,-0.167524
2,0.0,-0.050426,-0.076352,-0.349252,-0.044962,0.165122,-0.072568,-0.229522,0.283780,-0.444993,...,-0.109992,0.165122,0.165122,-0.072568,-0.229522,0.283780,-0.444993,-0.254056,-0.109992,-0.201719
3,0.0,0.107717,0.096648,-0.349252,-0.044962,0.175567,-0.008155,-0.043301,0.054969,-0.404020,...,-0.027588,0.175567,0.175567,-0.008155,-0.043301,0.054969,-0.404020,-0.240722,-0.027588,-0.008737
4,0.0,-0.059704,-0.075183,-0.349252,-0.044962,0.175567,-0.008155,-0.043301,0.054969,-0.404020,...,-0.027588,0.175567,0.175567,-0.008155,-0.043301,0.054969,-0.404020,-0.240722,-0.027588,-0.008737
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,0.0,-0.062591,-0.072291,-0.349252,-0.044962,0.276904,-0.028743,0.209360,0.163927,0.204885,...,-0.063950,0.276904,0.276904,-0.028743,0.209360,0.163927,0.204885,-0.135472,-0.063950,0.051787
95658,0.0,-0.046371,-0.072291,-0.349252,-0.044962,0.167759,-0.062526,-0.211742,0.251093,-0.398330,...,-0.098667,0.167759,0.167759,-0.062526,-0.211742,0.251093,-0.398330,-0.251156,-0.098667,-0.176151
95659,0.0,-0.054643,-0.080251,-0.349252,-0.044962,0.167759,-0.062526,-0.211742,0.251093,-0.398330,...,-0.098667,0.167759,0.167759,-0.062526,-0.211742,0.251093,-0.398330,-0.251156,-0.098667,-0.176151
95660,0.0,-0.030151,-0.056047,-0.349252,-0.044962,0.204153,-0.059427,-0.187412,0.163927,0.149116,...,-0.093538,0.204153,0.204153,-0.059427,-0.187412,0.163927,0.149116,-0.207473,-0.093538,-0.165662
95661,0.0,-0.054968,-0.079926,-0.349252,-0.044962,0.204153,-0.059427,-0.187412,0.163927,0.149116,...,-0.093538,0.204153,0.204153,-0.059427,-0.187412,0.163927,0.149116,-0.207473,-0.093538,-0.165662

In [53]:
from xverse.transformer import WOE

In [54]:
X = df.drop(columns=["FraudResult"])
y = df["FraudResult"]

In [55]:
cat_cols = X.select_dtypes(include=["object", "string"]).columns

In [58]:
X = X.copy()

cat_cols = X.select_dtypes(include=["object", "string"]).columns
num_cols = X.select_dtypes(include=["number"]).columns

In [59]:
X[cat_cols] = X[cat_cols].fillna("Missing")
X[num_cols] = X[num_cols].fillna(X[num_cols].median())

In [60]:
def split_features(df):
    cat_cols = df.select_dtypes(include=["object", "string"]).columns
    num_cols = df.select_dtypes(include=["number"]).columns
    return cat_cols, num_cols


cat_cols, num_cols = split_features(X)

In [61]:
cat_cols, num_cols

(Index(['TransactionId', 'BatchId', 'AccountId', 'SubscriptionId', 'CustomerId',
        'CurrencyCode', 'ProviderId', 'ProductId', 'ProductCategory',
        'ChannelId'],
       dtype='str'),
 Index(['CountryCode', 'Amount', 'Value', 'PricingStrategy',
        'TotalTransactionAmount_x', 'AvgTransactionAmount_x',
        'MaxTransactionAmount_x', 'MinTransactionAmount_x',
        'TransactionCount_x', 'TotalValue_x', 'AvgValue_x',
        'TotalTransactionAmount_y', 'TotalTransactionAmount',
        'AvgTransactionAmount_y', 'MaxTransactionAmount_y',
        'MinTransactionAmount_y', 'TransactionCount_y', 'TotalValue_y',
        'AvgValue_y', 'StdTransactionAmount', 'TransactionHour',
        'TransactionDay', 'TransactionMonth', 'TransactionYear'],
       dtype='str'))

In [67]:
import numpy as np

X = X.replace([np.inf, -np.inf], np.nan)
X = X.fillna("Missing")

In [69]:
for col in cat_cols:
    print("\n", col)
    print(X[col].value_counts().head(10))

 TransactionId
TransactionId
TransactionId_76871     1
TransactionId_73770     1
TransactionId_26203     1
TransactionId_380       1
TransactionId_28195     1
TransactionId_23223     1
TransactionId_118063    1
TransactionId_100640    1
TransactionId_51905     1
TransactionId_130161    1
Name: count, dtype: int64

 BatchId
BatchId
BatchId_67019     28
BatchId_51870     16
BatchId_113893    14
BatchId_127204    12
BatchId_116835    10
BatchId_88001      9
BatchId_49408      7
BatchId_110084     7
BatchId_86880      6
BatchId_4233       6
Name: count, dtype: int64

 AccountId
AccountId
AccountId_4841    30893
AccountId_4249     4457
AccountId_4840     1738
AccountId_3206     1105
AccountId_318      1070
AccountId_10        965
AccountId_3595      465
AccountId_751       411
AccountId_2648      359
AccountId_2314      356
Name: count, dtype: int64

 SubscriptionId
SubscriptionId
SubscriptionId_3829    32630
SubscriptionId_4429     4457
SubscriptionId_1372     1105
SubscriptionId_3087     1070
SubscriptionId_4346      965
SubscriptionId_1749      465
SubscriptionId_919       411
SubscriptionId_1311      359
SubscriptionId_4722      356
SubscriptionId_652       350
Name: count, dtype: int64

 CustomerId
CustomerId
CustomerId_7343    4091
CustomerId_3634    2085
CustomerId_647     1869
CustomerId_1096     784
CustomerId_4033     778
CustomerId_3066     612
CustomerId_2528     610
CustomerId_2728     586
CustomerId_3078     573
CustomerId_806      557
Name: count, dtype: int64

 CurrencyCode
CurrencyCode
UGX    95662
Name: count, dtype: int64

 ProviderId
ProviderId
ProviderId_4    38189
ProviderId_6    34186
ProviderId_5    14542
ProviderId_1     5643
ProviderId_3     3084
ProviderId_2       18
Name: count, dtype: int64

 ProductId
ProductId
ProductId_6     32635
ProductId_3     24344
ProductId_10    15384
ProductId_15    11964
ProductId_1      2885
ProductId_4      2403
ProductId_21     1512
ProductId_11     1377
ProductId_19      965
ProductId_14      789
Name: count, dtype: int64

 ProductCategory
ProductCategory
financial_services    45405
airtime               45027
utility_bill           1920
data_bundles           1613
tv                     1279
ticket                  216
movies                  175
transport                25
other                     2
Name: count, dtype: int64

 ChannelId
ChannelId
ChannelId_3    56935
ChannelId_2    37141
ChannelId_5     1048
ChannelId_1      538
Name: count, dtype: int64

In [70]:
drop_cols = [
    "TransactionId",
    "BatchId"
]

X = X.drop(columns=drop_cols)

In [71]:
for col in ["CustomerId", "AccountId", "SubscriptionId"]:
    freq = X[col].value_counts(normalize=True)
    X[col + "_freq"] = X[col].map(freq)

In [72]:
X = X.drop(columns=["CustomerId", "AccountId", "SubscriptionId"])

In [73]:
woe_cols = [
    "ProviderId",
    "ProductId",
    "ProductCategory",
    "ChannelId"
]

In [76]:
def collapse_rare(series, min_freq=0.01):
    freq = series.value_counts(normalize=True)
    allowed = freq[freq >= min_freq].index
    return series.where(series.isin(allowed), "Other")

In [79]:
cat_cols = X.select_dtypes(include=["object", "string"]).columns

In [80]:
for col in cat_cols:
    if col in X.columns:
        X[col] = collapse_rare(X[col], min_freq=0.01)

In [81]:
def get_feature_groups(df):
    cat_cols = df.select_dtypes(include=["object", "string"]).columns
    num_cols = df.select_dtypes(include=["number"]).columns
    return cat_cols, num_cols

In [83]:
import numpy as np

# Replace inf / -inf with NaN first
X = X.replace([np.inf, -np.inf], np.nan)

# Fill missing values
X = X.fillna("Missing")

In [84]:
cat_cols = X.select_dtypes(include=["object", "string"]).columns

for col in cat_cols:
    # group rare categories into "Other"
    freq = X[col].value_counts(normalize=True)

    rare = freq[freq < 0.01].index
    X[col] = X[col].replace(rare, "Other")

In [85]:
import numpy as np

np.seterr(divide='ignore', invalid='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [86]:
import numpy as np

# Handle infinities
X = X.replace([np.inf, -np.inf], np.nan)

# Fill missing values (required for WoE stability)
X = X.fillna("Missing")

# Reduce rare category instability
cat_cols = X.select_dtypes(include=["object", "string"]).columns

for col in cat_cols:
    freq = X[col].value_counts(normalize=True)
    rare = freq[freq < 0.01].index
    X[col] = X[col].replace(rare, "Other")

# Optional: suppress warnings
np.seterr(divide='ignore', invalid='ignore')

{'divide': 'ignore', 'over': 'warn', 'under': 'ignore', 'invalid': 'ignore'}

In [87]:
from category_encoders import WOEEncoder

woe = WOEEncoder(
    cols=cat_cols,
    handle_missing='value',
    handle_unknown='value',
    sigma=0.1   # smoothing
)

X_woe = woe.fit_transform(X, y)

,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,...,TotalValue_y,AvgValue_y,StdTransactionAmount,TransactionHour,TransactionDay,TransactionMonth,TransactionYear,CustomerId_freq,AccountId_freq,SubscriptionId_freq
0,-0.693137,0.0,NaN,NaN,NaN,7.193826,-0.046371,-0.072291,2018-11-15 02:18:49+00:00,-0.349252,...,-0.244587,-0.095799,-0.167524,2,15,11,2018,0.001244,0.000690,0.000690
1,-0.693137,0.0,NaN,NaN,7.431111,NaN,-0.054643,-0.080251,2018-11-15 02:19:08+00:00,-0.349252,...,-0.244587,-0.095799,-0.167524,2,15,11,2018,0.001244,0.322939,0.341097
2,-0.693137,0.0,NaN,NaN,NaN,7.193826,-0.050426,-0.076352,2018-11-15 02:44:21+00:00,-0.349252,...,-0.254056,-0.109992,-0.201719,2,15,11,2018,0.000021,0.000021,0.000021
3,-0.693137,0.0,9.26087,6.566003,8.518442,7.193826,0.107717,0.096648,2018-11-15 03:32:55+00:00,-0.349252,...,-0.240722,-0.027588,-0.008737,3,15,11,2018,0.000397,0.000272,0.000272
4,-0.693137,0.0,NaN,NaN,7.431111,NaN,-0.059704,-0.075183,2018-11-15 03:34:21+00:00,-0.349252,...,-0.240722,-0.027588,-0.008737,3,15,11,2018,0.000397,0.322939,0.341097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,-0.693137,0.0,NaN,NaN,7.431111,NaN,-0.062591,-0.072291,2019-02-13 09:54:09+00:00,-0.349252,...,-0.135472,-0.063950,0.051787,9,13,2,2019,0.005990,0.322939,0.341097
95658,-0.693137,0.0,NaN,NaN,NaN,7.193826,-0.046371,-0.072291,2019-02-13 09:54:25+00:00,-0.349252,...,-0.251156,-0.098667,-0.176151,9,13,2,2019,0.000449,0.000282,0.000282
95659,-0.693137,0.0,NaN,NaN,7.431111,NaN,-0.054643,-0.080251,2019-02-13 09:54:35+00:00,-0.349252,...,-0.251156,-0.098667,-0.176151,9,13,2,2019,0.000449,0.322939,0.341097
95660,-0.693137,0.0,NaN,NaN,NaN,7.193826,-0.030151,-0.056047,2019-02-13 10:01:10+00:00,-0.349252,...,-0.207473,-0.093538,-0.165662,10,13,2,2019,0.005478,0.003659,0.003659
95661,-0.693137,0.0,NaN,NaN,7.431111,NaN,-0.054968,-0.079926,2019-02-13 10:01:28+00:00,-0.349252,...,-0.207473,-0.093538,-0.165662,10,13,2,2019,0.005478,0.322939,0.341097